{% set version = "2.0-29" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-superlearner
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SuperLearner_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SuperLearner/SuperLearner_{{ version }}.tar.gz
  sha256: 236b03f969f4880680abb7f818bbbd92926ac3cb30b55560e3ee4d25d1572b3c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cvauc
    - r-gam >=1.15
    - r-nnls
  run:
    - r-base
    - r-cvauc
    - r-gam >=1.15
    - r-nnls

test:
  commands:
    - $R -e "library('SuperLearner')"           # [not win]
    - "\"%R%\" -e \"library('SuperLearner')\""  # [win]

about:
  home: https://github.com/ecpolley/SuperLearner
  license: GPL-3.0-only
  summary: Implements the super learner prediction method and contains a library of prediction algorithms to be used in the super learner.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: SuperLearner
# Type: Package
# Title: Super Learner Prediction
# Version: 2.0-25
# Date: 2019-08-05
# Authors@R: c(person("Eric", "Polley", email = "polley.eric@mayo.edu", role = c("aut", "cre")), person("Erin", "LeDell", role = c("aut")), person("Chris", "Kennedy", role = c("aut")), person("Sam", "Lendle", role = c("ctb")), person("Mark", "van der Laan", role = c("aut", "ths")))
# Maintainer: Eric Polley <polley.eric@mayo.edu>
# Description: Implements the super learner prediction method and contains a library of prediction algorithms to be used in the super learner.
# License: GPL-3
# URL: https://github.com/ecpolley/SuperLearner
# Depends: R (>= 2.14.0), nnls,
# Imports: cvAUC
# Suggests: arm, bartMachine, biglasso, bigmemory, caret, class, devtools, e1071, earth, extraTrees, gam (>= 1.15), gbm, genefilter, ggplot2, glmnet, ipred, KernelKnn, kernlab, knitr, lattice, LogicReg, MASS, mlbench, nloptr, nnet, party, polspline, prettydoc, quadprog, randomForest, ranger, RhpcBLASctl, ROCR, rmarkdown, rpart, SIS, speedglm, spls, sva, testthat, xgboost (>= 0.6)
# LazyLoad: yes
# VignetteBuilder: knitr, rmarkdown
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2019-08-07 21:52:38 UTC; mri5365
# Author: Eric Polley [aut, cre], Erin LeDell [aut], Chris Kennedy [aut], Sam Lendle [ctb], Mark van der Laan [aut, ths]
# Repository: CRAN
# Date/Publication: 2019-08-09 22:20:02 UTC
