appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: WofNTvePD/5uA93HkxCHItGkzWf8DI1YKaQA6kbwE0ISX3KEJkHij+lsRaUVg1sErUzwONv5JHLnEXLCXT3F5KiPm/UVZ7y4oZarjocnXnq+UxQFD/LX/NCrgYQ7TFBxe7346+MPaYHdyazO8tvjRhPICvo38tiyQUq3qyXugQGH/xMQ2a189ecgrIYM7Birgj1vjpUbiTHwr3Ku5jJb3Ya/1fNF2S3K+Z6A2jEqxkEt6c2/tCoRM6H+yEVrviGhIORMWKHhONL+MD6RP6WEURmf6KLCtlTN9qY57XzCzmHn/71W0RYgvJ+kxq36UJGK5aRybygbZAGGL3b1Ij+e36EhprFeyi24ansp0ZQVZ/u+0ZQbci4eoumdB865mN9C6oJQ2VAA3/jAM1f1vc75zxGMiHKKxWDdawQL0B38MrzghIpJtINxM4Wf9joKc5iQWTbdSTBUDG2TCZ2QAuqJzBtH81enyAbvmdI1Q8vhEulmt4PdV58df0Lasivz74K5ELfPo6NKyl9Y6aZosc4f1AE94C2UNTdMVlB9RS8NuRM78mrvpxiBfRryqlXbPzztIKYlsHmNDdJc7cxyXZVxpl8vgGc1dajfjEhc6gjcZ87kMb6Kkx+LSfv+r5EYbrNhcWRNrMiopg9pUP/UopByhijv1znOka9Ba8vc7uYL330=}
bot:
  automerge: true
