travis:
  secure:
    BINSTAR_TOKEN: n/6DfPXvAnSrV1kufcqWWL2CTt5ZvHzlDTBilCcgpGf9yzMkmin1bA3dx8+Wq7/EP0ucdab+ttpbMi7aFZXb0iNk0ytWCnnpM+gI5UcLsbdia8wpHYQObRuQQhDbBofbdhtIPFok7uU0r6mAEVugCDuU7G8oBP58I5lgB+Oyz1mwHEvzL0OigebIrXvyqcoGe7cNKd8UU9nSuKO+Kr8Mn1mSurU05wQz9ucGfKZPtyEQ+IzbART6o7RSJ8JIkpZoyidUNyuRPs6XsOfQZmYU/+dfM3VGh/xZ+N+35o0nQxwMXI50Siu+3uNgCZ3DvBFgtJnO44q6ya78G/Ojbyffz3jW9K5v43eYQOJmb1FHXZzm/oK6iY5x5FZZoxdPPs3kHYZKGB4gw8nPOzp7AaAsOHWu7VCJxs54yQ0tTZjx3HdwtUShdkFwfw6uxYbGzWrVntSbOAF7uDdyev83rYzWME4iK3dhAVqFTUWoVEG6dH7hW2XVl5t5Ge8yU4PtoKiiiuS44c2zJme89Lg3VMS1MfUsoLWrFHP9KE4/fBDxRsduuuzWd5zZd3Pej0JB0l11kVjQ4WzVKUK6PyeADarmLd8d+t5S/4j7/czFKRh/lfnhJ+tjzdO3ieUFICdplgTQ+9JmA/EwG6XDmm29pfm/a+Js8GRWKb04mxQFuHousRs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
